[0m06:13:43.630855 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab0e28db020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab0e2b7cf20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab0e27856a0>]}


============================== 06:13:43.635448 | 00e63a3b-a628-4b24-9ce9-c470c7156275 ==============================
[0m06:13:43.635448 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:13:43.636145 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/ubuntu/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:13:43.649567 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/ubuntu/.dbt')}
[0m06:13:43.650238 [info ] [MainThread]: Creating dbt configuration folder at 
[0m06:14:07.815581 [debug] [MainThread]: Starter project path: /home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/include/starter_project
[0m06:14:07.817698 [info ] [MainThread]: 
Your new dbt project "first_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m06:14:07.818722 [info ] [MainThread]: Setting up your profile.
[0m06:15:24.198486 [error] [MainThread]: Encountered an error:

[0m06:15:24.200556 [error] [MainThread]: Traceback (most recent call last):
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SP25_DS5111_rcs2mh/env/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m06:15:24.204418 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 100.633, "process_in_blocks": "72952", "process_kernel_time": 0.22378, "process_mem_max_rss": "159692", "process_out_blocks": "80", "process_user_time": 2.083837}
[0m06:15:24.204888 [debug] [MainThread]: Command `dbt init` failed at 06:15:24.204785 after 100.63 seconds
[0m06:15:24.205239 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab0e670f1a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab0ded78d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab0dba3f1a0>]}
[0m06:15:24.205559 [debug] [MainThread]: Flushing usage events
[0m06:15:24.220109 [debug] [MainThread]: An error was encountered while trying to flush usage events
